# Generated by Django 6.0 on 2025-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series/'),
        ),
    ]
