# Generated by Django 6.0 on 2025-12-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='episodes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
