# Generated by Django 6.0 on 2025-12-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episodes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
